### ISSUE TITLE
Code for Edit Distance problem in Dynamic Programing

### ISSUE THREAD

**Issue by sayskar500** [HemangJoshi/hacktoberfest-2022#70]
**Is your feature request related to a problem? Please describe.**

Yes, my code is related to the famous dp problem edit distance which somehow hasn't been added to this repository.

**Describe the solution you'd like**

I would like to add the c++ code for Edit Distance to the repository under the folder DP. I have already raised a PR for it.

**Describe alternatives you've considered**

Iterative dp may be a better option in some cases, but the overall time complexity remains the same.

**Additional context**

Given two strings _word1_ and _word2_, return the minimum number of operations required to convert _word1_ to _word2_.

**Comment by HemangJoshi** [comment]
your pr was reviewed and some changes were required before merging it.
pls do look into it

**Comment by HemangJoshi** [comment]
if you still have any doubts pls continue else the issue will be closed after 24 hrs of inactivity.

**Comment by sayskar500** [comment]
No more doubts. Thanks for the clarification. Working on the request.

Thanks !
