### ISSUE TITLE
Should include codes covering basic c++ concepts

### ISSUE THREAD

**Issue by swarajmhatre** [HemangJoshi/hacktoberfest-2022#80]
I can share my own c++ codes on your repo. PLease assign me this issue.

**Comment by HemangJoshi** [comment]
sorry but this repo is only for intermediate-level C++ programs (mostly DSA and operating systems) if you want we can collab and create a repo for beginner-level programs too.
P.S: the new repository will not be under hacktoberfest.

**Comment by HemangJoshi** [comment]
if you still have any doubts pls continue else the issue will be closed after 24 hrs of inactivity.
