### ISSUE TITLE
Morris Traversal 

### ISSUE THREAD

**Issue by xenacro** [HemangJoshi/hacktoberfest-2022#89]
Should include a file explaning morris traversal of binary tree.

**Comment by HemangJoshi** [comment]
you can but first pls add comments as they make it easier for beginners to understand and develop there skill

**Comment by HemangJoshi** [comment]
if you still have any doubts pls continue else the issue will be closed after 24 hrs of inactivity.

**Comment by xenacro** [comment]
Using Morris Traversal, we can traverse the tree without using stack and recursion. The idea of Morris Traversal is based on [Threaded Binary Tree](http://en.wikipedia.org/wiki/Threaded_binary_tree). In this traversal, we first create links to Inorder successor and print the data using these links, and finally revert the changes to restore original tree.
